#!/usr/bin/env python
"""Generate the starter .cube LUTs shipped in fixtures/luts.

Written rather than downloaded, so their provenance is this file and their licence is the repo's.
Each is a 17-point 3D LUT — small enough to read, big enough to grade smoothly.

    uv run python scripts/make_luts.py

* ``identity`` — changes nothing. The acceptance test for auto-lut compares an identity-graded
  image against its original (SSIM > 0.98), so a wrong pipeline shows up as a difference rather
  than being masked by a strong look.
* ``warm-film`` — lifted shadows, warm highlights, slightly reduced blue.
* ``teal-orange`` — the familiar split tone: cool shadows, warm skin-range midtones.
"""

from __future__ import annotations

import argparse
from collections.abc import Callable
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
LUTS = REPO_ROOT / "fixtures" / "luts"
SIZE = 17

Transform = Callable[[float, float, float], tuple[float, float, float]]


def _clamp(value: float) -> float:
    return 0.0 if value < 0.0 else 1.0 if value > 1.0 else value


def identity(r: float, g: float, b: float) -> tuple[float, float, float]:
    return r, g, b


def warm_film(r: float, g: float, b: float) -> tuple[float, float, float]:
    lift = 0.04  # milky shadows, as film prints tend to have
    r2 = lift + (1 - lift) * r**0.92
    g2 = lift + (1 - lift) * g**0.97
    b2 = lift * 1.2 + (1 - lift) * b**1.06
    return _clamp(r2), _clamp(g2), _clamp(b2)


def teal_orange(r: float, g: float, b: float) -> tuple[float, float, float]:
    luma = 0.2126 * r + 0.7152 * g + 0.0722 * b
    # Push shadows towards teal and highlights towards orange, strongest at the extremes.
    shadow = (1 - luma) ** 2
    highlight = luma**2
    r2 = r + 0.10 * highlight - 0.05 * shadow
    g2 = g + 0.02 * highlight + 0.01 * shadow
    b2 = b - 0.08 * highlight + 0.10 * shadow
    return _clamp(r2), _clamp(g2), _clamp(b2)


LOOKS: dict[str, tuple[str, Transform]] = {
    "identity": ("Neutral pass-through, for verifying the pipeline", identity),
    "warm-film": ("Lifted shadows and warm highlights", warm_film),
    "teal-orange": ("Cool shadows, warm midtones", teal_orange),
}


def write_cube(name: str, title: str, transform: Transform, size: int = SIZE) -> Path:
    """Write one .cube file. Blue varies slowest, red fastest — the format's required order."""
    LUTS.mkdir(parents=True, exist_ok=True)
    lines = [
        f"# {title}",
        "# Generated by scripts/make_luts.py — part of immich-addons, MIT licensed.",
        f'TITLE "{name}"',
        f"LUT_3D_SIZE {size}",
        "DOMAIN_MIN 0.0 0.0 0.0",
        "DOMAIN_MAX 1.0 1.0 1.0",
        "",
    ]
    last = size - 1
    for bi in range(size):
        for gi in range(size):
            for ri in range(size):
                out = transform(ri / last, gi / last, bi / last)
                lines.append(" ".join(f"{channel:.6f}" for channel in out))

    dest = LUTS / f"{name}.cube"
    dest.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return dest


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--size", type=int, default=SIZE, help=f"LUT cube size (default {SIZE})")
    args = parser.parse_args(argv)

    for name, (title, transform) in LOOKS.items():
        dest = write_cube(name, title, transform, args.size)
        print(f"wrote {dest.relative_to(REPO_ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
